### ISSUE TITLE
Beginner questions

### ISSUE THREAD

**Issue by zemingyu** [bokkypoobah/BabysittersClubDApp#1]
1. In settings.txt there is ```IPCFILE=ipc:./testchain/geth.ipc```
What is IPC? How does it differ from ```geth --dev```?

2. What's the purpose of ```INCLUDEJS, JSONSUMMARY``` and ```JSONEVENTS``` in 01test1.sh?

3. What does perl -le do?
```CURRENTTIMES=`perl -le "print scalar localtime $CURRENTTIME"```

4. What's does ```1:-test``` do? Does $ means it's a environment variable?
```MODE=${1:-test}```

**Comment by bokkypoobah** [comment]
1. When you run `00_runGeth.sh`, it will set up a `--dev` blockchain in the `./testchain` subdirectory. 

```$ ./00_runGeth.sh
...
INFO [05-20|11:57:56] IPC endpoint opened                      url={your directory}/ClubEth/test/testchain/geth.ipc
```

An Inter-process Communication file is created in the `./testchain` subdirectory with the name `geth.ipc`. You can then use the command `geth attach ipc:/testchain/geth.ipc` for the second `geth` process to attach to the first `geth` process. More info on IPC at https://ethereum.stackexchange.com/questions/10681/what-are-ipc-and-rpc .

**Comment by bokkypoobah** [comment]
2. They are unused for this project, but I use them for other projects

**Comment by bokkypoobah** [comment]
3. Context

CURRENTTIME=\`date +%s\`
CURRENTTIMES=\`perl -le "print scalar localtime $CURRENTTIME"\`

The first line computes the number of seconds since 01/01/1970 (search for 'unixtime')

`$ date +%s`
`1526781849`

The second line computes the string equivalent of the unixtime variable

`$ perl -le "print scalar localtime 1526781849"`
`Sun May 20 12:04:09 2018`

**Comment by bokkypoobah** [comment]
4. See https://unix.stackexchange.com/questions/122845/using-a-b-for-variable-assignment-in-scripts
